export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAIL = 'FETCH_COUNTRIES_FAIL';

export const FETCH_COUNTRY = 'FETCH_COUNTRY';
export const FILTER_REGION = 'FILTER_REGION';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const SEARCH_COUNTRY_SUCCESS = 'SEARCH_COUNTRY_SUCCESS';
export const SEARCH_COUNTRY_FAIL = 'SEARCH_COUNTRY_FAIL';

export const LOADING_COUNTRIES = 'LOADING_COUNTRIES';
